import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
      <div className="z-10 top-0 left-0 absolute text-foreground w-full flex flex-col h-screen justify-between">
        <main>{children}</main>
      </div>
      </body>
    </html>
  );
}
